# DataFrame

Creating a DataFrame

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# DataFrame using the dictionary
data = {
    'Name': ['John','Anna','Peter','Linda'],
    'Age' :[28,34,29,42],
    'City':['New York','Paris','Berlin','London'],
    'Salary':[6500,7000,6200,8500]    
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York    6500
1   Anna   34     Paris    7000
2  Peter   29    Berlin    6200
3  Linda   42    London    8500

In [6]:
# DataFrame using the list
data_list = [
    ['Jhon',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]
df1 = pd.DataFrame(data_list)
cols = ['Name','Age','City','Salary']
# Adding the col name
df1 = pd.DataFrame(data_list,columns=cols)

In [7]:
df1

    Name  Age      City  Salary
0   Jhon   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selecting and Indexing of Columns

In [8]:
df1

    Name  Age      City  Salary
0   Jhon   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
# Selecting Name
df1['Name']

0     Jhon
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [10]:
# Slecting multiple col
df1[['Name','City']]

    Name      City
0   Jhon  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Creating a new column

In [13]:
df1['Occupation'] = ['Farmer','Doctor','Engineer','Doctor']
df1

    Name  Age      City  Salary Occupation
0   Jhon   28  New York   65000     Farmer
1   Anna   34     Paris   70000     Doctor
2  Peter   29    Berlin   62000   Engineer
3  Linda   42    London   85000     Doctor

Removing Columns

In [17]:
df1.drop('Occupation',axis=1,inplace=True)  #inplace= Ture removes the data competely form the memory as well

In [18]:
df1

    Name  Age      City  Salary
0   Jhon   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
# Remoing multiple data
df1.drop(['City','Age'],axis=1)  #axis=0 for horizontal ||| axis=1 for cols

    Name  Salary
0   Jhon   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [ ]:
# Droping the rows
df1.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

Selecting Rows

In [ ]:
df1.loc[[0,1]] # loc--> location

   Name  Age      City  Salary
0  Jhon   28  New York   65000
1  Anna   34     Paris   70000

In [27]:
df1.iloc[[0,1]]   #iloc --> index location

   Name  Age      City  Salary
0  Jhon   28  New York   65000
1  Anna   34     Paris   70000

Selecting Subsets of Rows and Columns

In [30]:
df1.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [31]:
df1.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Selection

In [32]:
df1

    Name  Age      City  Salary
0   Jhon   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [33]:
# Selection the people age>30
df1[df1["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
# age>30 and must form the paris city
df1[(df["Age"]>30) & (df1["City"] =="Paris")]  #remove the round brakets and check something

   Name  Age   City  Salary
1  Anna   34  Paris   70000